server.port=8082
spring.application.name=ms-vidasalud-appointments

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vidasalud_appointments
spring.datasource.username=postgres
spring.datasource.password=123456789

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Azure Entra ID - JWT Validation
# Azure Entra ID - JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/001834fd-b68a-4e6a-a718-6d859787b926/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://09d40f2a-29ea-43c0-8d74-b89ba284c778,09d40f2a-29ea-43c0-8d74-b89ba284c778

logging.level.org.springframework.security=TRACE