server.port=8080
spring.application.name=ms-vidasalud-bff

# Azure Entra ID - JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/001834fd-b68a-4e6a-a718-6d859787b926/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://09d40f2a-29ea-43c0-8d74-b89ba284c778,09d40f2a-29ea-43c0-8d74-b89ba284c778

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=catalog-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/catalog/**

spring.cloud.gateway.routes[1].id=appointments-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/appointments/**

spring.cloud.gateway.routes[2].id=audit-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/audit/**

spring.cloud.gateway.routes[3].id=report-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/report/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=TRACE