server.port=8085
spring.application.name=ms-vidasalud-notify

# Disable Data Source auto-configuration since notify has no DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Azure Entra ID - JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/001834fd-b68a-4e6a-a718-6d859787b926/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://09d40f2a-29ea-43c0-8d74-b89ba284c778,09d40f2a-29ea-43c0-8d74-b89ba284c778

logging.level.org.springframework.security=TRACE